npm:
  publish: false
git:
  commit: true
  commitMessage: "chore(release): ${version}"
  tag: true
  requireCommits: true
  changelog: "npx auto-changelog --stdout --commit-limit false"

plugins:
  "@release-it/conventional-changelog":
    infile: CHANGELOG.md
    preset:
      name: conventionalcommits
      types:
        - type: feat
          section: Features
        - type: fix
          section: Bug Fixes
        - tyep: docs
          section: Documentation